//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.2.0
//     from Assets/Scripts/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""ShipMovement"",
            ""id"": ""0f441f78-2bbc-4131-9eb8-45803027820e"",
            ""actions"": [
                {
                    ""name"": ""SurgeAxis"",
                    ""type"": ""Value"",
                    ""id"": ""1a873773-2f17-49fe-8914-e01f48725385"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SwayAxis"",
                    ""type"": ""Value"",
                    ""id"": ""bda3cad0-84ec-447d-ae90-cbb989056d6c"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""HeaveAxis"",
                    ""type"": ""Value"",
                    ""id"": ""3f10d351-4636-4d1b-b982-b95347d71992"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RollAxis"",
                    ""type"": ""Value"",
                    ""id"": ""c28533bf-f695-4a1a-87bb-c8dc0dcae92a"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PitchAxis"",
                    ""type"": ""Value"",
                    ""id"": ""27f929f3-21b9-4a11-8e60-5849a75b8678"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""YawAxis"",
                    ""type"": ""Value"",
                    ""id"": ""3b94fee8-feae-4e89-b79c-3dc3b0ac8f86"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ToggleFA"",
                    ""type"": ""Button"",
                    ""id"": ""17e1e3aa-e9df-480c-8ddf-1133b2f373b4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""54fd0638-bdd3-41fe-8c93-0151beea6c18"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SurgeAxis"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""0c1d135f-33ef-46a7-833c-8e072e70db94"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SurgeAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""80db9640-b70b-407c-b0e6-192b1652ed60"",
                    ""path"": ""<XInputController>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SurgeAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""b1889ec0-7b90-4aab-9b2e-ffe4c06cc7b9"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SurgeAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""31022412-78d7-4a4e-adc3-9e88006b811c"",
                    ""path"": ""<XInputController>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SurgeAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""48ced733-a462-44af-8a9f-648e9b12277d"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwayAxis"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""ac74117b-8843-46c2-be8f-a1b72372e204"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwayAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""571aa4ef-3560-4906-b9ec-321054b17251"",
                    ""path"": ""<XInputController>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwayAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""1af4008a-a3e3-4fff-9eff-43f161f6dab1"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwayAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""75e65e33-9b4a-4485-97be-ad887664befc"",
                    ""path"": ""<XInputController>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwayAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""21280dbb-abe7-41a1-bedb-8e6d15d2917f"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HeaveAxis"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""d1d2f2bf-339b-4bcb-94d5-4d4902bbb85d"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HeaveAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""8f1a4c0a-f500-448c-8600-49dd6e9b5862"",
                    ""path"": ""<XInputController>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HeaveAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""980ef393-a160-4a6f-9735-49bd4007d619"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HeaveAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""887fb792-c7ac-45c9-9229-398410388262"",
                    ""path"": ""<XInputController>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HeaveAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""5d4c740c-d9a7-4303-86d5-b87b60c007d3"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RollAxis"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""7e6ea069-4bdf-410d-be53-c5dc850734eb"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RollAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""25a9f05f-e8f6-4fac-94f9-71ddbe7726f4"",
                    ""path"": ""<XInputController>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RollAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""5c6e88a9-dd22-407b-8fb0-c20e512ca108"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RollAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""ab6e6b1c-9294-4cd8-8250-96bd542ae307"",
                    ""path"": ""<XInputController>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RollAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""7e518097-abf4-4149-bb7f-1eff4ed68f95"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PitchAxis"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""c86f5e2a-645f-486b-ba65-70e5f8731b1b"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PitchAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""f6a79e6f-94fa-4d67-8bcd-31d3df9d82cf"",
                    ""path"": ""<XInputController>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PitchAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""aa2ff192-5464-4405-ab6c-d3e1d6d5eb50"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PitchAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""8f9e7c21-5bf1-4f66-b6bf-c763b9c7188a"",
                    ""path"": ""<XInputController>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PitchAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""2bee5173-a379-4754-81a2-3ca16942f232"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""YawAxis"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""0de1a81b-c97d-4b12-a576-da7ee17d1f4c"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""YawAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""3d65e940-5535-498e-8f7e-8101c91bf867"",
                    ""path"": ""<XInputController>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""YawAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""7546ea69-7420-4019-8771-72fb69cb3f46"",
                    ""path"": ""<Keyboard>/o"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""YawAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""dd66921b-b7b9-40e6-813a-aa8a4c28bd8a"",
                    ""path"": ""<XInputController>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""YawAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""656a8cf7-0a12-48ac-87f8-4af5725cea20"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleFA"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7c0a808c-194b-4a2d-9351-2f9bdf90badc"",
                    ""path"": ""<XInputController>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleFA"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Weapons"",
            ""id"": ""658b2234-119a-4c6f-a546-5bc6f9cd23b8"",
            ""actions"": [
                {
                    ""name"": ""Fire1"",
                    ""type"": ""Button"",
                    ""id"": ""fa6e1a8f-b83c-4839-8163-10759518a2db"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""6669b10a-37a0-47c6-937d-5c2adb64c4d4"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fire1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a158329f-2f6c-40e5-8dcb-6192b5c56f13"",
                    ""path"": ""<XInputController>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fire1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5a48b059-0606-4e44-898d-ee6cc9e5e322"",
                    ""path"": ""<HID::Microsoft SideWinder Precision 2 Joystick>/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fire1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // ShipMovement
        m_ShipMovement = asset.FindActionMap("ShipMovement", throwIfNotFound: true);
        m_ShipMovement_SurgeAxis = m_ShipMovement.FindAction("SurgeAxis", throwIfNotFound: true);
        m_ShipMovement_SwayAxis = m_ShipMovement.FindAction("SwayAxis", throwIfNotFound: true);
        m_ShipMovement_HeaveAxis = m_ShipMovement.FindAction("HeaveAxis", throwIfNotFound: true);
        m_ShipMovement_RollAxis = m_ShipMovement.FindAction("RollAxis", throwIfNotFound: true);
        m_ShipMovement_PitchAxis = m_ShipMovement.FindAction("PitchAxis", throwIfNotFound: true);
        m_ShipMovement_YawAxis = m_ShipMovement.FindAction("YawAxis", throwIfNotFound: true);
        m_ShipMovement_ToggleFA = m_ShipMovement.FindAction("ToggleFA", throwIfNotFound: true);
        // Weapons
        m_Weapons = asset.FindActionMap("Weapons", throwIfNotFound: true);
        m_Weapons_Fire1 = m_Weapons.FindAction("Fire1", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // ShipMovement
    private readonly InputActionMap m_ShipMovement;
    private IShipMovementActions m_ShipMovementActionsCallbackInterface;
    private readonly InputAction m_ShipMovement_SurgeAxis;
    private readonly InputAction m_ShipMovement_SwayAxis;
    private readonly InputAction m_ShipMovement_HeaveAxis;
    private readonly InputAction m_ShipMovement_RollAxis;
    private readonly InputAction m_ShipMovement_PitchAxis;
    private readonly InputAction m_ShipMovement_YawAxis;
    private readonly InputAction m_ShipMovement_ToggleFA;
    public struct ShipMovementActions
    {
        private @PlayerControls m_Wrapper;
        public ShipMovementActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @SurgeAxis => m_Wrapper.m_ShipMovement_SurgeAxis;
        public InputAction @SwayAxis => m_Wrapper.m_ShipMovement_SwayAxis;
        public InputAction @HeaveAxis => m_Wrapper.m_ShipMovement_HeaveAxis;
        public InputAction @RollAxis => m_Wrapper.m_ShipMovement_RollAxis;
        public InputAction @PitchAxis => m_Wrapper.m_ShipMovement_PitchAxis;
        public InputAction @YawAxis => m_Wrapper.m_ShipMovement_YawAxis;
        public InputAction @ToggleFA => m_Wrapper.m_ShipMovement_ToggleFA;
        public InputActionMap Get() { return m_Wrapper.m_ShipMovement; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ShipMovementActions set) { return set.Get(); }
        public void SetCallbacks(IShipMovementActions instance)
        {
            if (m_Wrapper.m_ShipMovementActionsCallbackInterface != null)
            {
                @SurgeAxis.started -= m_Wrapper.m_ShipMovementActionsCallbackInterface.OnSurgeAxis;
                @SurgeAxis.performed -= m_Wrapper.m_ShipMovementActionsCallbackInterface.OnSurgeAxis;
                @SurgeAxis.canceled -= m_Wrapper.m_ShipMovementActionsCallbackInterface.OnSurgeAxis;
                @SwayAxis.started -= m_Wrapper.m_ShipMovementActionsCallbackInterface.OnSwayAxis;
                @SwayAxis.performed -= m_Wrapper.m_ShipMovementActionsCallbackInterface.OnSwayAxis;
                @SwayAxis.canceled -= m_Wrapper.m_ShipMovementActionsCallbackInterface.OnSwayAxis;
                @HeaveAxis.started -= m_Wrapper.m_ShipMovementActionsCallbackInterface.OnHeaveAxis;
                @HeaveAxis.performed -= m_Wrapper.m_ShipMovementActionsCallbackInterface.OnHeaveAxis;
                @HeaveAxis.canceled -= m_Wrapper.m_ShipMovementActionsCallbackInterface.OnHeaveAxis;
                @RollAxis.started -= m_Wrapper.m_ShipMovementActionsCallbackInterface.OnRollAxis;
                @RollAxis.performed -= m_Wrapper.m_ShipMovementActionsCallbackInterface.OnRollAxis;
                @RollAxis.canceled -= m_Wrapper.m_ShipMovementActionsCallbackInterface.OnRollAxis;
                @PitchAxis.started -= m_Wrapper.m_ShipMovementActionsCallbackInterface.OnPitchAxis;
                @PitchAxis.performed -= m_Wrapper.m_ShipMovementActionsCallbackInterface.OnPitchAxis;
                @PitchAxis.canceled -= m_Wrapper.m_ShipMovementActionsCallbackInterface.OnPitchAxis;
                @YawAxis.started -= m_Wrapper.m_ShipMovementActionsCallbackInterface.OnYawAxis;
                @YawAxis.performed -= m_Wrapper.m_ShipMovementActionsCallbackInterface.OnYawAxis;
                @YawAxis.canceled -= m_Wrapper.m_ShipMovementActionsCallbackInterface.OnYawAxis;
                @ToggleFA.started -= m_Wrapper.m_ShipMovementActionsCallbackInterface.OnToggleFA;
                @ToggleFA.performed -= m_Wrapper.m_ShipMovementActionsCallbackInterface.OnToggleFA;
                @ToggleFA.canceled -= m_Wrapper.m_ShipMovementActionsCallbackInterface.OnToggleFA;
            }
            m_Wrapper.m_ShipMovementActionsCallbackInterface = instance;
            if (instance != null)
            {
                @SurgeAxis.started += instance.OnSurgeAxis;
                @SurgeAxis.performed += instance.OnSurgeAxis;
                @SurgeAxis.canceled += instance.OnSurgeAxis;
                @SwayAxis.started += instance.OnSwayAxis;
                @SwayAxis.performed += instance.OnSwayAxis;
                @SwayAxis.canceled += instance.OnSwayAxis;
                @HeaveAxis.started += instance.OnHeaveAxis;
                @HeaveAxis.performed += instance.OnHeaveAxis;
                @HeaveAxis.canceled += instance.OnHeaveAxis;
                @RollAxis.started += instance.OnRollAxis;
                @RollAxis.performed += instance.OnRollAxis;
                @RollAxis.canceled += instance.OnRollAxis;
                @PitchAxis.started += instance.OnPitchAxis;
                @PitchAxis.performed += instance.OnPitchAxis;
                @PitchAxis.canceled += instance.OnPitchAxis;
                @YawAxis.started += instance.OnYawAxis;
                @YawAxis.performed += instance.OnYawAxis;
                @YawAxis.canceled += instance.OnYawAxis;
                @ToggleFA.started += instance.OnToggleFA;
                @ToggleFA.performed += instance.OnToggleFA;
                @ToggleFA.canceled += instance.OnToggleFA;
            }
        }
    }
    public ShipMovementActions @ShipMovement => new ShipMovementActions(this);

    // Weapons
    private readonly InputActionMap m_Weapons;
    private IWeaponsActions m_WeaponsActionsCallbackInterface;
    private readonly InputAction m_Weapons_Fire1;
    public struct WeaponsActions
    {
        private @PlayerControls m_Wrapper;
        public WeaponsActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Fire1 => m_Wrapper.m_Weapons_Fire1;
        public InputActionMap Get() { return m_Wrapper.m_Weapons; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(WeaponsActions set) { return set.Get(); }
        public void SetCallbacks(IWeaponsActions instance)
        {
            if (m_Wrapper.m_WeaponsActionsCallbackInterface != null)
            {
                @Fire1.started -= m_Wrapper.m_WeaponsActionsCallbackInterface.OnFire1;
                @Fire1.performed -= m_Wrapper.m_WeaponsActionsCallbackInterface.OnFire1;
                @Fire1.canceled -= m_Wrapper.m_WeaponsActionsCallbackInterface.OnFire1;
            }
            m_Wrapper.m_WeaponsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Fire1.started += instance.OnFire1;
                @Fire1.performed += instance.OnFire1;
                @Fire1.canceled += instance.OnFire1;
            }
        }
    }
    public WeaponsActions @Weapons => new WeaponsActions(this);
    public interface IShipMovementActions
    {
        void OnSurgeAxis(InputAction.CallbackContext context);
        void OnSwayAxis(InputAction.CallbackContext context);
        void OnHeaveAxis(InputAction.CallbackContext context);
        void OnRollAxis(InputAction.CallbackContext context);
        void OnPitchAxis(InputAction.CallbackContext context);
        void OnYawAxis(InputAction.CallbackContext context);
        void OnToggleFA(InputAction.CallbackContext context);
    }
    public interface IWeaponsActions
    {
        void OnFire1(InputAction.CallbackContext context);
    }
}
